version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /data/nginx/default:/user/share/nginx/html
version: '3'
services:
  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - /data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /data/nginx/security.conf:/etc/nginx/security.conf
      - /data/nginx/config:/etc/nginx/conf.d
      - /data/nginx/sites:/data/nginx
